### ISSUE TITLE
Organize import

### ISSUE THREAD

**Issue by kaitoii11** [Medha-B/unetdl4j#1]
Should remove unused imports. To organize import on eclipse, see the link below.
https://dzone.com/articles/organize-imports-eclipse#:~:text=To%20enable%20this%2C%20go%20to,remove%20the%20unused%20imports%20automatically.

**Comment by Medha-B** [comment]
Removed used imports. 
Please let me know if it works.

**Comment by Medha-B** [comment]
Removed unused imports. 
Please let me know if there is any problem yet remaining regarding this issue.

**Comment by Medha-B** [comment]
May I close this issue?
