### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by kaitoii11** [Medha-B/unetdl4j#17]
Update the README to describe how to run the code step by step.
For example, how/where to download the image files and how to run an inference.

**Comment by Medha-B** [comment]
Updated the README. Please let me know what I should add to improve.

**Comment by kaitoii11** [comment]
You should specify where the dataset should be downloaded since we are hardcoding the path to the dataset.

**Comment by Medha-B** [comment]
I have mentioned the "dataset folder under the working directory". Would I need to elaborate on the working directory part?

**Comment by kaitoii11** [comment]
Sorry I wasn't specific enough. Where in the dataset directory do we download the dataset? There are couple of subdirectories in there so we should specify.

**Comment by Medha-B** [comment]
Does this https://github.com/Medha-B/unetdl4j/commit/ee0e773c202b30f12bae03fbfcc2d805a64c7c56 look better? Should I do the same for other classes? Or would you want it to be written some other way?

**Comment by kaitoii11** [comment]
Yes, it looks better now. Maybe consider using markdown syntax for links.
https://guides.github.com/features/mastering-markdown/

Also,  we should add an argument to the example execution.
For example,  `% java -cp target/segmentation-1.0-SNAPSHOT-bin.jar org.sbml.spatial.segmentation.UnetTrainAndTest </path/to/dataset>`.

**Comment by Medha-B** [comment]
Hi!
I used markdown syntax for the links. Please let me know if it looks correct. 
Why should we add an argument to the example execution though? Does that make any changes to how the program executes? Especially since the </path/to/dataset> is hardcoded.

**Comment by kaitoii11** [comment]
It looks great! 

> Why should we add an argument to the example execution though? Does that make any changes to how the program executes? Especially since the </path/to/dataset> is hardcoded.

Taking `UnetLoadAndTest.java` as an example, you can see that the image is hardcoded. If we do not give any arguments.
https://github.com/Medha-B/unetdl4j/blob/b44567594b3ecb09fabd2165a7663f15041ed697/src/main/java/org/sbml/spatial/segmentation/UnetLoadAndTest.java#L40-L44

However, if we give a path to the images, we can run the code with any given file/directory which is much more flexible. 

> Especially since the </path/to/dataset> is hardcoded.

What do you mean by hardcoded? This indicates that a user can specify the path to the dataset.

**Comment by Medha-B** [comment]
Will check on my end and make the changes soon. Thanks!

**Comment by Medha-B** [comment]
Hello!
Quick question: Does doing this: ```% java -cp target/segmentation-1.0-SNAPSHOT-bin.jar org.sbml.spatial.segmentation.UnetTrainAndTest </path/to/dataset>``` suffice or would it have to be something like this: ```% java -cp target/segmentation-1.0-SNAPSHOT-bin.jar org.sbml.spatial.segmentation.UnetTrainAndTest ~/dataset/small_dataset```?
Also, do we want to do this for every class (like UnetLoadAndTest, UnetTrainAndSave etc.)?

**Comment by kaitoii11** [comment]
> Quick question: Does doing this: % java -cp target/segmentation-1.0-SNAPSHOT-bin.jar org.sbml.spatial.segmentation.UnetTrainAndTest </path/to/dataset> suffice or would it have to be something like this: % java -cp target/segmentation-1.0-SNAPSHOT-bin.jar org.sbml.spatial.segmentation.UnetTrainAndTest ~/dataset/small_dataset?

We don't know where exactly the dataset will be so it should be the former. But it might be better to replace ` </path/to/dataset>` to  `</path/to/small_dataset>`  

> Also, do we want to do this for every class (like UnetLoadAndTest, UnetTrainAndSave, etc.)?

Looking at the code, it would probably make sense to do so. Since we are hardcoding the path when not given an argument.

https://github.com/Medha-B/unetdl4j/blob/b44567594b3ecb09fabd2165a7663f15041ed697/src/main/java/org/sbml/spatial/segmentation/UnetLoadAndTest.java#L40-L44

**Comment by Medha-B** [comment]
Hi!
I have made the suggested changes. Please do take a look and let me know if these look fine. Also, I made a change in UnetIOU.java regarding the argument assigned to pathToInferredImage. Please take a look at that too (commit https://github.com/Medha-B/unetdl4j/pull/21/commits/d28c79e7f092db36720ae355c321ff9757a29d2d).
Pull Request: https://github.com/Medha-B/unetdl4j/pull/21
