### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by kaitoii11** [Medha-B/unetdl4j#18]
We need to add an opensouce license to this repository. Maybe Apache or MIT?

**Comment by Medha-B** [comment]
Since XitoSBML uses Apache License, maybe we can use the same for this repository?

**Comment by funasoul** [comment]
Yes, please add Apache License to the repo.
-- 
Akira

**Comment by Medha-B** [comment]
Does this work https://github.com/Medha-B/unetdl4j/pull/19? May I merge this PR?

**Comment by Medha-B** [comment]
Added License to README.

**Comment by Medha-B** [comment]
May I close this issue?
