### ISSUE TITLE
Modify file path to be usable with Linux and Mac

### ISSUE THREAD

**Issue by kaitoii11** [Medha-B/unetdl4j#2]
File paths such as
`File rootDir = new File("C:\\Users\\Subroto\\Desktop\\small_dataset");`
is only applicable to windows.

`File.separator` should be used to generate a file path.
https://stackoverflow.com/questions/30120813/how-do-i-provide-a-file-path-in-mac-os-x-while-creating-a-file-in-java

Also, use `System.getProperty` (maybe `System.getProperty("user.dir")`) to generate a path instead of hard-coding them which may destroy other user's files.

**Comment by Medha-B** [comment]
Modified the file paths.
Please let me know if there is any problem yet remaining regarding this issue.

**Comment by kaitoii11** [comment]
It's better! But we shouldn't assume that the target files are either under `home` or `Desktop`.
We should probably assume that the target files are under the folder where this code is cloned at. For instance `xxx\unetdl4j\small_dataset\`

So it is better to use `System.getPropter("user.dir") + File.separator + <Folder name to dataset>`. In this case, `System.getPropter("user.dir")` will be `xxx\unetd;4j`

PS: Would you mind creating a pull request for any related changes to this issue?

**Comment by Medha-B** [comment]
So should I change the code to System.getPropter("user.dir") + File.separator + <Folder name to dataset>? Even if it does not work on my end?
I would have to learn about the pull requests. Would I have to use the 'new pull request' option on this git page or is it possible to do so using Eclipse?

**Comment by kaitoii11** [comment]
> So should I change the code to System.getPropter("user.dir") + File.separator + ? Even if it does not work on my end?

Yes, it would be a simpler solution. As for your environment, you should move the dataset file to wherever the `System.getPropter("user.dir") + File.separator + ? ` points to and your code should work.
Also, if you have added the dataset into this repository folder, you should create a [gitignore](https://docs.github.com/en/github/using-git/ignoring-files) file and ignore all folders containing the dataset. This way we can avoid downloading/uploading the dataset making clone/push much faster.

>I would have to learn about the pull requests. Would I have to use the 'new pull request' option on this git page or is it possible to do so using Eclipse?

You should probably read this [link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/proposing-changes-to-your-work-with-pull-requests) to get a general understanding of how to create a pull request. 
In eclipse, you should be able to create a new branch and push it but to create a pull request you have to do that on GitHub.

**Comment by Medha-B** [comment]
Thanks. Will get working on it.

**Comment by Medha-B** [comment]
Please see the pull request 'Modified the path again' for branch_modifyPath and let me know if it works right.

**Comment by kaitoii11** [comment]
You may close this issue as well.
