### ISSUE TITLE
Abstract the code to avoid repetition

### ISSUE THREAD

**Issue by kaitoii11** [Medha-B/unetdl4j#4]
The same snippets are found on multiple files. Try using functions and other abstractions to avoid repetitions.
Keep in mind the [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principal.

**Comment by Medha-B** [comment]
Working on it.

**Comment by Medha-B** [comment]
Please check https://github.com/Medha-B/unetdl4j/pull/14 and let me know in case of any discrepancies.

**Comment by Medha-B** [comment]
May I close this issue?
